### ISSUE TITLE
Issue on page /notebooks/20-ModelFitting-NLLS.html

### ISSUE THREAD

**Issue by vitorlcferreira** [mhasoba/TheMulQuaBio#107]
The link for **Lecture** here does not exists anymore!
https://mhasoba.github.io/TheMulQuaBio/notebooks/20-ModelFitting-NLLS.html#:~:text=The%20last%20two,on%20this%20below).

Should be updated to:
https://github.com/mhasoba/TheMulQuaBio/tree/master/content/lectures/NLLS

**Comment by mhasoba** [comment]
Fixed, thanks!
