### ISSUE TITLE
Issue on page /notebooks/01-Unix.html

### ISSUE THREAD

**Issue by TJCanterbury** [mhasoba/TheMulQuaBio#11]
For grep exercise
`wget https://raw.githubusercontent.com/mhasoba/TheMulQuaBio/master/data/spawannxs.txt #Cool!`

gives 

`
--2020-10-05 13:47:39--  https://raw.githubusercontent.com/mhasoba/TheMulQuaBio/master/data/spawannxs.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-05 13:47:39 ERROR 404: Not Found.
`

**Comment by fwimp** [comment]
Needs to be changed to `https://raw.githubusercontent.com/mhasoba/TheMulQuaBio/master/content/data/spawannxs.txt`
