### ISSUE TITLE
Issue on page /notebooks/01-Unix.html

### ISSUE THREAD

**Issue by ldswaby** [mhasoba/TheMulQuaBio#17]
There seems to be a 'Y' and an 'R' in the E.coli.fasta sequence, generating slightly different answers to Q5 of the practical depending how you choose to calculate the ratio of T/A to G/C bases in the sequence:

_(base) Lukes-MBP:Data lukeswaby-petts$ grep -n '[^ATGC]' E.coli.fasta 
1:>E.coli
350:CAGACCTTTAGCAGC**Y**TGACGGTCCACGATCGGTTGCATTTCGTTAAATGCTTTCTGTGC
2374:GTTATGCTATTGCACCGGCGTTCACCT**R**GCGTCCGGATGATAAAACCAATTTTACCTTCC_

**Comment by mhasoba** [comment]
Good point Will make this clear in the instructions. Basically, the calculation should be done by keeping these extra letters in place. R and Y are used to to represent bases where there is uncertainty about their identity, with R denoting purine (A or G) and Y pyrimidine (C or T) ribonucleotides. No agreed symbols exist for the other possible combinations.
