### ISSUE TITLE
05-Python_I.html/A program-with-control-flows example - Uses old python formatting

### ISSUE THREAD

**Issue by fwimp** [mhasoba/TheMulQuaBio#22]
We should really refactor the examples to use the "new" (circa 2006) style python string formatting using the `.format()` method of the string.

Also including a link to https://www.pyformat.info would be good as this has some excellent examples of how to do python string formatting.

**Comment by davidorme** [comment]
Or even skip that and go to the actual new style :-)

https://realpython.com/python-f-strings/

D

On 14 Oct 2020, at 11:10, Francis Windram <notifications@github.com<mailto:notifications@github.com>> wrote:

This email from notifications@github.com<mailto:notifications@github.com> originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



We should really refactor the examples to use the "new" (circa 2006) style python string formatting using the .format() method of the string.

Also including a link to https://www.pyformat.info<https://www.pyformat.info/> would be good as this has some excellent examples of how to do python string formatting.

**Comment by fwimp** [comment]
Oooh absolutely, didn't do it before just because 3.6 wasn't a standard install until relatively recently. We should probably cover all methods to do it.
