### ISSUE TITLE
Issue on page /notebooks/Appendix-NLLS-Python.html

### ISSUE THREAD

**Issue by pablolich** [mhasoba/TheMulQuaBio#41]
The las section of this chapter (Exercise) should only have the first line of comment on each cell. I can't modify it myself because I can't find Appendix-NLLS-Python in the github repo. Do you know why?

**Comment by mhasoba** [comment]
@pablolich, this notebook is here:     https://github.com/mhasoba/TheMulQuaBio/blob/master/content/notebooks/Appendix-NLLS-Python.ipynb 

Is this still an issue?

**Comment by pablolich** [comment]
No!
