### ISSUE TITLE
Walrus Operator

### ISSUE THREAD

**Issue by fwimp** [mhasoba/TheMulQuaBio#57]
Is it time to write a small thing introducing the walrus operator (`:=`) from Python 3.8?

I'm still not super sure exactly when I should use it yet, but it might be useful to keep students up to date with the more recent python versions:

https://realpython.com/lessons/assignment-expressions/

https://www.python.org/dev/peps/pep-0572/#examples

**Comment by mhasoba** [comment]
I tend to agree with @kokestu here, so I am putting this on the back burner, to be revisited in next year's revisions

**Comment by fwimp** [comment]
Looking at this and still remain unconvinced that it would be useful to include in the course at present. Closing for now but will re-open if it actually comes up in a common use case, then we can revisit.
