### ISSUE TITLE
Issue on page /notebooks/04-LaTeX.html

### ISSUE THREAD

**Issue by fwindram** [mhasoba/TheMulQuaBio#8]
"A first LaTeX example" is in as an ipython code block, but formatted like markdown. Should instead be in a markdown block so it doesn't try to execute the code fence:

```
  File "<ipython-input-1-06e4abbacf33>", line 1
    ```
    ^
SyntaxError: invalid syntax
```

**Comment by mhasoba** [comment]
fixed
